### ISSUE TITLE
PHP errors in Email Notification Revised v3.0 

### ISSUE THREAD

**Issue by GeoffAU** [zakkak/q2a-email-notifications-revised#5]
Here is an error log of some problems with v3.0 of this plugin:

[30-Apr-2015 06:06:18 America/Denver] PHP Warning:  mysql_result() expects parameter 1 to be resource, object given in qa-plugin/email-notification-revised/qa-user-email-notifications-event.php on line 233
[30-Apr-2015 06:06:18 America/Denver] PHP Notice:  Undefined variable: subs in qa-plugin/email-notification-revised/qa-user-email-notifications-event.php on line 159
[30-Apr-2015 06:06:18 America/Denver] PHP Warning:  strtr(): The second argument is not an array in qa-plugin/email-notification-revised/qa-user-email-notifications-event.php on line 159

Any ideas how to correct this?

**Comment by zakkak** [comment]
I would focus on the undefined variable `subs`.  I guess you need to define it as a global variable earlier in the file to make it visible there.  To the best of my knowledge it used to work as is in earlier php versions, but after a certain point php requires explicit definition of global variables.  Probably there are other places affected by this change.

**Comment by justinputney** [comment]
I'm using the old email notification plugin and I just upgraded Q2A to be compatible with PHP5.5.
I received the same error.
Q2A is now using mysqli instead of mysql (which is deprecated).

This change resolved the error for me:
`//return mysql_result($res, 0) == 1;`
`mysqli_data_seek($res, 0);`
`$row = mysqli_fetch_array($res);`
`return $row[0] == 1;`

I haven't done extensive testing, but it might be worth a try if you're having the same problem.

**Comment by zakkak** [comment]
Please create a pull request if you find it's working fine.

**Comment by justinputney** [comment]
My first attempt at pull request: https://github.com/sparticus1701/Q2A-Email-Notifications/pull/5

**Comment by zakkak** [comment]
Hi @justinputney the pull request should be made on my fork and not the original repository of @sparticus1701, unless your fixes are for it.

Additionally, the pull request you created is to merge my patches on @sparticus1701 repository and not you patches on my fork or @sparticus1701 repository.

If you want to add your changes on my fork you will need to:

1. fork it (visit https://github.com/zakkak/q2a-email-notifications-revised and click fork).
2. edit the corresponding files and commit the changes (on your fork)
3. visit https://github.com/zakkak/q2a-email-notifications-revised and click new pull request.  Choose zakkak/q2a-email-notifications-revised as the base fork and your fork as the head fork and proceed to create the pull request.

If you find this too much of a hustle please just send in a patch file.

Thanks

**Comment by shortsteps** [comment]
@justinputney suggestion worked for me too (Q2A v. 1.7.4 on CentOS 7.3 with PHP v. 5.4.16 and MariaDB Server v. 5.5.52).
I had to change it manually because I guess this request has never been pulled/committed on this fork nor in @sparticus1701 repo. I think it would be very useful.

Thanks a lot guys
